FLAGS= -Wall -Wextra -Wshadow -Wno-unused-result -D_GLIBCXX_DEBUG -fsanitize=address -fsanitize=undefined -fno-sanitize-recover

run_10928:
	@g++ 10928.cpp $(FLAGS) &&./a.out<d.in

run_256:
	@g++ 256.cpp $(FLAGS) &&./a.out<d.in

run_11643:
	@g++ 11643.cpp $(FLAGS) &&./a.out<d.in

run_10006:
	@g++ 10006.cpp $(FLAGS) &&./a.out<d.in

run_227:
	@g++ 227.cpp $(FLAGS) &&./a.out<d.in

java:
	@javac Main.java && java Main < d.in

run_10042:
	@g++ 10042.cpp $(FLAGS) &&./a.out<d.in

#gyROp8jh
